# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Keep Calm
subtitle: and Drink Coffe
author: William Seo
email: wseo88@gmail.com
description: > # Things Will Seo says, thinks and believes. But first, let me drink my coffee.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://wseo88.github.io" # the base hostname & protocol for your site
twitter: wseo88
github: wseo88
facebook: wseo88

# Build settings
markdown: kramdown
